name: grocerystoreapp
description: Store side mobile application for the grocery app project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  device_info: ^0.4.2+4
  firebase_storage: ^3.1.6
  random_string: ^2.1.0
  file_picker: ^1.12.0
  pdf: ^1.8.0
  flutter_full_pdf_viewer: ^1.0.6
  printing: ^3.4.0
  path_provider: ^1.6.8
  firebase_core: ^0.4.0
  map: ^0.1.0+1
  latlng: ^0.0.2
  gps: ^0.1.1
  firebase_auth: ^0.15.2
  firebase_database: ^3.1.5
  persistent_bottom_nav_bar: ^2.0.5
  flutter_spinkit: ^4.1.2+1
  shared_preferences: ^0.5.10
  sqflite: ^1.3.1
#  fluttertoast: ^7.0.2
  rflutter_alert: ^1.0.3
  google_fonts: ^1.1.0
  url_launcher: ^5.5.2
  permissions_plugin: ^1.1.4
  google_sign_in: ^4.5.1
  geocoder: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
     - images/

  fonts:
     - family:  Custom_icons_iconsdart
       fonts:
         - asset: fonts/Custom_icons_iconsdart.ttf
     - family: Poppins
       fonts:
         - asset: fonts/Poppins-Regular.ttf
